# qbittorrent_nox/config.yaml
name: "qBittorrent-Nox"
version: "5.1.0-0"
slug: "qbittorrent_nox"
description: "qBittorrent-Nox running as a Home Assistant add-on."
url: "https://github.com/qbittorrent/qBittorrent"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
map:
  - config:rw
  - share:rw
  - media:rw
  - addon_config:rw
ports:
  6881/tcp: 6881
  6881/udp: 6881
  8080/tcp: 8080
options:
  QBT_EULA: "ACCEPTEULA"
  QBT_VERSION: "5.1.1-1"
  QBT_WEBUI_PORT: 8080
  TZ: "Europe/Budapest"
schema:
  QBT_EULA: "str"
  QBT_VERSION: "str"
  QBT_WEBUI_PORT: "port"
  TZ: "str"
host_network: false
privileged:
  - NET_ADMIN
